

CREATE DATABASE IF NOT EXISTS DB_learn;





CREATE TABLE IF NOT EXISTS users(
    id BIGINT AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE
);

-- edit in table users column id => userId 
-- ALTER TABLE users 
-- CHANGE COLUMN id usreId BIGINT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY;
-- -- تنفيذ امر التعديل 
-- DESCRIBE users;

USE DB_learn;
CREATE TABLE IF NOT EXISTS posts(
    postId BIGINT AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
    usreId INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (usreId) REFERENCES users(usreId)
);


SHOW TABLES;